#!/usr/bin/env bash
# Initialize variables for hours and minutes
hour=0

# Use a while loop to display the time
while [ $hour -lt 12 ]; do
  echo "Hour: $hour"
  minute=1
  while [ $minute -le 59 ]; do
    echo $minute
    ((minute++))
  done
  ((hour++))
done
