#!/usr/bin/env bash

# Display a header with column names for user-oriented format
printf "%-10s %-10s %-25s %-10s %-15s %-40s\n" "PID" "PPID" "COMMAND" "USER" "TTY" "CMDLINE"

# Use 'ps' command to list all processes with hierarchy, including those without TTY
ps -e -o pid,ppid,comm,user,tty,cmd --forest --no-headers | while read -r line; do
    # Extract relevant information from 'ps' output
    pid=$(echo $line | awk '{print $1}')
    ppid=$(echo $line | awk '{print $2}')
    cmd=$(echo $line | awk '{print $3}')
    user=$(echo $line | awk '{print $4}')
    tty=$(echo $line | awk '{print $5}')
    cmdline=$(echo $line | awk '{print $6}')

    # Display the information in the user-oriented format
    printf "%-10s %-10s %-25s %-10s %-15s %-40s\n" "$pid" "$ppid" "$cmd" "$user" "$tty" "$cmdline"
done

