#!/usr/bin/env bash
# Display a header with column names for user-oriented format
printf "%-10s %-10s %-25s %-10s %-15s %-40s\n" "PID" "PPID" "COMMAND" "USER" "TTY" "CMDLINE"

# Use 'ps' command to list all processes, including those without TTY
ps aux --forest | grep -v '^USER' | while read -r line; do
    # Extract relevant information from 'ps' output
        pid=$(echo $line | awk '{print $2}')
	    ppid=$(echo $line | awk '{print $3}')
	        cmd=$(echo $line | awk '{print $11}')
		    user=$(echo $line | awk '{print $1}')
		        tty=$(echo $line | awk '{print $7}')
			    cmdline=$(echo $line | awk '{$1=""; $2=""; $3=""; $4=""; $5=""; $6=""; $7=""; $8=""; $9=""; $10=""; $11=""; $12=""; $13=""; print $0}')

			        # Display the information in the user-oriented format
				    printf "%-10s %-10s %-25s %-10s %-15s %-40s\n" "$pid" "$ppid" "$cmd" "$user" "$tty" "$cmdline"
			    done
			    

